Added commands to protocol
vasthecat/operating-systems pull request #7
Opened 2022-04-10 12:28 UTC by vasthecat

Turns out that if password isn't found, client halts.
```
./brute -x & ./brute -c -h $(./encr -p qqq)
```

2022-04-10 12:32 UTC, vasthecat commented
With these changes server seems to not release used port after end of program. Can't find location of this bug for now.

2022-04-10 12:55 UTC, hnarkaytis requested changes

2022-04-10 12:55 UTC, hnarkaytis commented on server.c
> +    close(client_sfd);
what about TCP fin to client?
shutdown (fd, SHUT_RDWR);

2022-04-10 13:40 UTC, hnarkaytis requested changes

2022-04-10 13:40 UTC, hnarkaytis commented on server.c
> +    sleep(0.1);
https://linux.die.net/man/3/sleep
sleep takes integer value as an argument. sleep (0.1) -> sleep (0);

2022-04-10 21:19 UTC, hnarkaytis requested changes

2022-04-10 21:19 UTC, hnarkaytis commented on server.c
> +    close(client_sfd);
Why shutdown was removed?

2022-04-11 16:32 UTC, hnarkaytis approved these changes

2022-04-11 17:58 UTC, merged